#!/usr/bin/env bash
# ============================================================================
# build.sh — compiles the modular src/ tree into dist/server-tools.sh.
# See docs/ARCHITECTURE.md. Never edit dist/ by hand.
# ============================================================================
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="${ROOT_DIR}/src"
OUT_FILE="${ROOT_DIR}/dist/server-tools.sh"
VERSION="$(tr -d '[:space:]' <"${ROOT_DIR}/VERSION")"

# Concatenation order is significant: header first, then core, modules,
# menu, and the entrypoint last. New src files must be added here.
SOURCES=(
  00-header.sh
  core/colors.sh
  core/log.sh
  core/ui.sh
  core/utils.sh
  core/state.sh
  core/backup.sh
  modules/detect.sh
  modules/sysinfo.sh
  modules/profile.sh
  modules/sysctl.sh
  modules/dns.sh
  modules/swap.sh
  modules/limits.sh
  modules/extras.sh
  modules/perf.sh
  modules/security.sh
  modules/vpn.sh
  modules/ipv6.sh
  modules/kernel.sh
  modules/mirror.sh
  modules/installer.sh
  modules/tools.sh
  modules/selfupdate.sh
  modules/optimize.sh
  modules/doctor.sh
  menu.sh
  99-main.sh
)

mkdir -p "${ROOT_DIR}/dist"

{
  printf '#!/usr/bin/env bash\n'
  printf '# =========================================================================\n'
  printf '# ServerTools v%s — single-file build\n' "$VERSION"
  printf '# Generated from src/ by build.sh — DO NOT EDIT THIS FILE DIRECTLY.\n'
  printf '# https://github.com/Sir-Adnan/server-tools\n'
  printf '# =========================================================================\n'
  for src in "${SOURCES[@]}"; do
    printf '\n# ------------------------- src/%s -------------------------\n' "$src"
    # Strip per-file shebang/shellcheck directives; inject the version string.
    sed -e '\|^#!/usr/bin/env bash$|d' \
      -e '/^# shellcheck shell=bash$/d' \
      -e "s/@VERSION@/${VERSION}/g" \
      "${SRC_DIR}/${src}"
  done
} >"$OUT_FILE"

chmod +x "$OUT_FILE"
bash -n "$OUT_FILE"
printf 'Built %s (v%s, %s lines)\n' "$OUT_FILE" "$VERSION" "$(wc -l <"$OUT_FILE" | tr -d '[:space:]')"
