#!/usr/bin/env bash
# ============================================================
# VPN Server Optimizer (SAFE) — VLESS TCP Reality friendly
# - DOES NOT touch MTU
# - DOES NOT touch NIC ring buffers (ethtool)
# - Disables tcp_mtu_probing
# - Uses conservative socket buffer sizes to avoid bufferbloat
# - Optional DNS helper (without netplan hacks / ~. routing)
# ============================================================

set -Eeuo pipefail
IFS=$'\n\t'

VERSION="1.0.0-safe"
SCRIPT_NAME="vpn_optimizer_safe"

BACKUP_ROOT="/root/vpn_optimizer_backups"
LATEST_LINK="${BACKUP_ROOT}/latest"

LOG_FILE="/var/log/vpn_optimizer_safe.log"
if ! (touch "$LOG_FILE" >/dev/null 2>&1); then
  LOG_FILE="/tmp/vpn_optimizer_safe.log"
fi

# ---------- logging ----------
log() {
  local ts
  ts="$(date '+%F %T')"
  echo "[$ts] $*" | tee -a "$LOG_FILE" >/dev/null
}

die() {
  log "ERROR: $*"
  echo "ERROR: $*" >&2
  exit 1
}

need_root() {
  [[ "${EUID:-$(id -u)}" -eq 0 ]] || die "Run as root."
}

# ---------- backup ----------
_new_backup_dir() {
  mkdir -p "$BACKUP_ROOT"
  local d="${BACKUP_ROOT}/$(date '+%Y%m%d_%H%M%S')"
  mkdir -p "$d"
  ln -sfn "$d" "$LATEST_LINK"
  echo "$d"
}

backup_path() {
  # Copies file/symlink metadata into backup dir (best-effort)
  local p="$1"
  local bdir="$2"

  [[ -e "$p" || -L "$p" ]] || return 0

  local rel="${p#/}"
  local dest="${bdir}/${rel}"
  mkdir -p "$(dirname "$dest")"

  # Preserve symlinks as symlinks
  if [[ -L "$p" ]]; then
    local tgt
    tgt="$(readlink "$p")"
    ln -sfn "$tgt" "$dest"
  elif [[ -f "$p" ]]; then
    cp -a "$p" "$dest"
  else
    cp -a "$p" "$dest" 2>/dev/null || true
  fi
}

rollback_latest() {
  [[ -L "$LATEST_LINK" ]] || die "No latest backup found at $LATEST_LINK"
  local bdir
  bdir="$(readlink -f "$LATEST_LINK")"
  [[ -d "$bdir" ]] || die "Backup directory missing: $bdir"

  log "Rolling back from: $bdir"

  # Restore known paths we touch
  local paths=(
    "/etc/sysctl.d/99-vpn-opt.conf"
    "/etc/security/limits.d/99-vpn.conf"
    "/etc/systemd/system.conf"
    "/etc/resolv.conf"
    "/etc/systemd/resolved.conf"
    "/etc/systemd/resolved.conf.d/99-vpn-dns.conf"
  )

  for p in "${paths[@]}"; do
    local rel="${p#/}"
    local src="${bdir}/${rel}"
    if [[ -e "$src" || -L "$src" ]]; then
      mkdir -p "$(dirname "$p")"
      rm -rf "$p"
      if [[ -L "$src" ]]; then
        ln -sfn "$(readlink "$src")" "$p"
      else
        cp -a "$src" "$p"
      fi
      log "Restored: $p"
    fi
  done

  sysctl --system >/dev/null 2>&1 || true
  systemctl daemon-reexec >/dev/null 2>&1 || true
  systemctl restart systemd-resolved >/dev/null 2>&1 || true

  log "Rollback complete."
  echo "Rollback complete."
}

# ---------- system detection ----------
get_ram_mb() {
  awk '/MemTotal:/ {printf "%.0f\n", $2/1024}' /proc/meminfo 2>/dev/null || echo 0
}

get_default_iface() {
  ip route show default 0.0.0.0/0 2>/dev/null | awk '{print $5; exit}'
}

has_cmd() { command -v "$1" >/dev/null 2>&1; }

pick_congestion() {
  local avail
  avail="$(sysctl -n net.ipv4.tcp_available_congestion_control 2>/dev/null || true)"
  if echo "$avail" | grep -qw bbr; then
    echo "bbr"
  else
    echo "cubic"
  fi
}

pick_qdisc() {
  if tc qdisc add dev lo root fq >/dev/null 2>&1; then
    tc qdisc del dev lo root >/dev/null 2>&1 || true
    echo "fq"
  else
    echo "fq_codel"
  fi
}

# ---------- core: safe sysctl ----------
apply_sysctl_safe() {
  need_root
  local bdir; bdir="$(_new_backup_dir)"
  backup_path "/etc/sysctl.d/99-vpn-opt.conf" "$bdir"

  local RAM_MB; RAM_MB="$(get_ram_mb)"
  local BBR_ALGO; BBR_ALGO="$(pick_congestion)"
  local QDISC; QDISC="$(pick_qdisc)"

  # Conservative buffers (avoid bufferbloat on typical VPS)
  # Keep tcp_{r,w}mem max aligned with rmem_max/wmem_max.
  local RMAX WMAX
  if (( RAM_MB <= 1024 )); then
    RMAX=$(( 8 * 1024 * 1024 ))
    WMAX=$(( 8 * 1024 * 1024 ))
  elif (( RAM_MB <= 4096 )); then
    RMAX=$(( 16 * 1024 * 1024 ))
    WMAX=$(( 16 * 1024 * 1024 ))
  elif (( RAM_MB <= 8192 )); then
    RMAX=$(( 32 * 1024 * 1024 ))
    WMAX=$(( 32 * 1024 * 1024 ))
  else
    RMAX=$(( 64 * 1024 * 1024 ))
    WMAX=$(( 64 * 1024 * 1024 ))
  fi

  local CONNTRACK
  if (( RAM_MB <= 1024 )); then CONNTRACK=65536
  elif (( RAM_MB <= 4096 )); then CONNTRACK=262144
  else CONNTRACK=$((RAM_MB * 64)); fi
  (( CONNTRACK > 2000000 )) && CONNTRACK=2000000

  cat > /etc/sysctl.d/99-vpn-opt.conf <<EOF
# Generated by ${SCRIPT_NAME} ${VERSION}
# Focus: VLESS TCP Reality (stable, low-latency) / generic VPN forwarding
# NOTE: This file intentionally avoids MTU tweaks and NIC ring changes.

# Congestion control
net.core.default_qdisc=${QDISC}
net.ipv4.tcp_congestion_control=${BBR_ALGO}

# Backlogs (moderate, not insane)
net.core.somaxconn=8192
net.ipv4.tcp_max_syn_backlog=8192
net.core.netdev_max_backlog=16384

# TCP sanity
net.ipv4.tcp_syncookies=1
net.ipv4.tcp_slow_start_after_idle=0
net.ipv4.tcp_no_metrics_save=1
net.ipv4.tcp_fin_timeout=30
net.ipv4.tcp_keepalive_time=300
net.ipv4.tcp_keepalive_intvl=60
net.ipv4.tcp_keepalive_probes=5

# IMPORTANT: disable MTU probing (prevents runaway MTU shrink on lossy/filtered paths)
net.ipv4.tcp_mtu_probing=0

# Socket buffers (conservative to avoid bufferbloat)
net.core.rmem_max=${RMAX}
net.core.wmem_max=${WMAX}
net.core.rmem_default=262144
net.core.wmem_default=262144
net.ipv4.tcp_rmem=4096 87380 ${RMAX}
net.ipv4.tcp_wmem=4096 65536 ${WMAX}
net.ipv4.udp_rmem_min=16384
net.ipv4.udp_wmem_min=16384

# Routing / forwarding (VPN servers need this)
net.ipv4.ip_forward=1

# Conntrack sizing (helps NAT-heavy setups)
net.netfilter.nf_conntrack_max=${CONNTRACK}

# VM / files
vm.swappiness=10
fs.file-max=2097152
EOF

  sysctl --system >/dev/null 2>&1 || true
  log "Applied safe sysctl. BBR=${BBR_ALGO}, QDISC=${QDISC}, RMAX/WMAX=${RMAX} bytes."
  echo "Applied safe sysctl."
}

# ---------- limits ----------
apply_limits_safe() {
  need_root
  local bdir; bdir="$(_new_backup_dir)"
  backup_path "/etc/security/limits.d/99-vpn.conf" "$bdir"
  backup_path "/etc/systemd/system.conf" "$bdir"

  cat > /etc/security/limits.d/99-vpn.conf <<'EOF'
# Generated by vpn_optimizer_safe
* soft nofile 1048576
* hard nofile 1048576
root soft nofile 1048576
root hard nofile 1048576
EOF

  if [[ -f /etc/systemd/system.conf ]]; then
    grep -q '^DefaultLimitNOFILE=' /etc/systemd/system.conf && \
      sed -i 's/^DefaultLimitNOFILE=.*/DefaultLimitNOFILE=1048576/' /etc/systemd/system.conf || \
      echo "DefaultLimitNOFILE=1048576" >> /etc/systemd/system.conf
  else
    echo "DefaultLimitNOFILE=1048576" > /etc/systemd/system.conf
  fi

  systemctl daemon-reexec >/dev/null 2>&1 || true
  log "Applied limits (nofile 1048576)."
  echo "Applied limits."
}

# ---------- DNS helper (optional, minimal) ----------
set_dns_resolved() {
  local dns1="$1" dns2="$2"
  local bdir; bdir="$(_new_backup_dir)"
  backup_path "/etc/systemd/resolved.conf.d/99-vpn-dns.conf" "$bdir"
  backup_path "/etc/systemd/resolved.conf" "$bdir"
  backup_path "/etc/resolv.conf" "$bdir"

  mkdir -p /etc/systemd/resolved.conf.d
  cat > /etc/systemd/resolved.conf.d/99-vpn-dns.conf <<EOF
# Generated by vpn_optimizer_safe
[Resolve]
DNS=${dns1} ${dns2}
FallbackDNS=
EOF

  systemctl restart systemd-resolved >/dev/null 2>&1 || true
  log "Set DNS via systemd-resolved: ${dns1}, ${dns2}"
  echo "DNS set (systemd-resolved)."
}

set_dns_resolvconf() {
  local dns1="$1" dns2="$2"
  local bdir; bdir="$(_new_backup_dir)"
  backup_path "/etc/resolv.conf" "$bdir"

  if [[ -L /etc/resolv.conf ]]; then
    echo "/etc/resolv.conf is a symlink. Refusing to overwrite it directly."
    echo "Use systemd-resolved option instead."
    return 1
  fi

  cat > /etc/resolv.conf <<EOF
nameserver ${dns1}
nameserver ${dns2}
EOF

  log "Set DNS via /etc/resolv.conf: ${dns1}, ${dns2}"
  echo "DNS set (/etc/resolv.conf)."
}

dns_apply() {
  local d1="$1" d2="$2"
  if systemctl is-active systemd-resolved >/dev/null 2>&1; then
    set_dns_resolved "$d1" "$d2"
  else
    set_dns_resolvconf "$d1" "$d2" || true
  fi
}

dns_reset() {
  need_root
  local bdir; bdir="$(_new_backup_dir)"
  backup_path "/etc/systemd/resolved.conf.d/99-vpn-dns.conf" "$bdir"
  rm -f /etc/systemd/resolved.conf.d/99-vpn-dns.conf
  systemctl restart systemd-resolved >/dev/null 2>&1 || true
  log "Removed DNS override drop-in."
  echo "DNS override removed."
}

dns_menu() {
  need_root
  local choice
  echo
  echo "DNS:"
  echo " 1) Cloudflare  (1.1.1.1, 1.0.0.1)"
  echo " 2) Google      (8.8.8.8, 8.8.4.4)"
  echo " 3) Quad9       (9.9.9.9, 149.112.112.112)"
  echo " 4) Reset (remove our resolved drop-in if present)"
  echo " 0) Back"
  read -r -p "Select: " choice

  case "$choice" in
    1) dns_apply "1.1.1.1" "1.0.0.1" ;;
    2) dns_apply "8.8.8.8" "8.8.4.4" ;;
    3) dns_apply "9.9.9.9" "149.112.112.112" ;;
    4) dns_reset ;;
    0) return 0 ;;
    *) echo "Invalid." ;;
  esac
}

# ---------- swap (optional) ----------
setup_swap_2g() {
  need_root
  local bdir; bdir="$(_new_backup_dir)"
  backup_path "/etc/fstab" "$bdir"

  if swapon --show | grep -q .; then
    echo "Swap is already enabled."
    return 0
  fi

  local swapfile="/swapfile"
  if [[ -e "$swapfile" ]]; then
    echo "Swapfile exists but swap isn't active. Trying to enable..."
  else
    if has_cmd fallocate; then
      fallocate -l 2G "$swapfile" 2>/dev/null || dd if=/dev/zero of="$swapfile" bs=1M count=2048 status=none
    else
      dd if=/dev/zero of="$swapfile" bs=1M count=2048 status=none
    fi
    chmod 600 "$swapfile"
    mkswap "$swapfile" >/dev/null
  fi

  swapon "$swapfile"
  grep -q '^/swapfile ' /etc/fstab || echo "/swapfile none swap sw 0 0" >> /etc/fstab
  log "Swap enabled (2G)."
  echo "Swap enabled."
}

# ---------- legacy cleanup (from older optimizers) ----------
cleanup_legacy_risky() {
  need_root
  local bdir; bdir="$(_new_backup_dir)"

  # 1) Revert MTU to 1500 on default iface (runtime only)
  local IFACE; IFACE="$(get_default_iface || true)"
  if [[ -n "${IFACE:-}" ]]; then
    local cur
    cur="$(ip link show dev "$IFACE" 2>/dev/null | awk '/mtu/ {for(i=1;i<=NF;i++) if($i=="mtu"){print $(i+1); exit}}')"
    backup_path "/etc/netplan/99-vpn-override.yaml" "$bdir"
    if [[ -n "${cur:-}" && "$cur" != "1500" ]]; then
      ip link set dev "$IFACE" mtu 1500 2>/dev/null || true
      log "Set MTU=1500 on ${IFACE} (runtime). Previous: ${cur}"
    fi
  fi

  # 2) Remove netplan override from older script (if present)
  if [[ -f /etc/netplan/99-vpn-override.yaml ]]; then
    rm -f /etc/netplan/99-vpn-override.yaml
    if has_cmd netplan; then
      netplan generate >/dev/null 2>&1 || true
      netplan apply >/dev/null 2>&1 || true
    fi
    log "Removed legacy netplan override /etc/netplan/99-vpn-override.yaml"
  fi

  # 3) Remove older systemd-resolved drop-in that used '~.' routing / stub changes
  backup_path "/etc/systemd/resolved.conf.d/99-vpn_optimizer.conf" "$bdir"
  if [[ -f /etc/systemd/resolved.conf.d/99-vpn_optimizer.conf ]]; then
    rm -f /etc/systemd/resolved.conf.d/99-vpn_optimizer.conf
    systemctl restart systemd-resolved >/dev/null 2>&1 || true
    log "Removed legacy resolved drop-in /etc/systemd/resolved.conf.d/99-vpn_optimizer.conf"
  fi

  echo "Legacy risky tweaks cleaned up (best-effort)."
}

# ---------- status ----------
show_status() {
  local RAM_MB; RAM_MB="$(get_ram_mb)"
  local IFACE; IFACE="$(get_default_iface || true)"
  echo
  echo "Status:"
  echo " - Version: ${VERSION}"
  echo " - RAM: ${RAM_MB} MB"
  echo " - Default iface: ${IFACE:-unknown}"
  echo " - Congestion: $(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo '?')"
  echo " - Qdisc: $(sysctl -n net.core.default_qdisc 2>/dev/null || echo '?')"
  echo " - tcp_mtu_probing: $(sysctl -n net.ipv4.tcp_mtu_probing 2>/dev/null || echo '?')"
  echo " - rmem_max: $(sysctl -n net.core.rmem_max 2>/dev/null || echo '?')"
  echo " - wmem_max: $(sysctl -n net.core.wmem_max 2>/dev/null || echo '?')"
  echo " - Swap: $(swapon --show | awk 'NR==1{print ($1? "ON":"OFF")}' 2>/dev/null || echo OFF)"
  echo " - Latest backup: $(readlink -f "$LATEST_LINK" 2>/dev/null || echo none)"
  echo " - Log: $LOG_FILE"
}

# ---------- main menu ----------
main_menu() {
  need_root
  while true; do
    echo
    echo "============================================================"
    echo " VPN Optimizer (SAFE) for VLESS TCP Reality"
    echo "============================================================"
    echo " 1) Apply SAFE sysctl (no MTU, no ring, no MTU probing)"
    echo " 2) Apply SAFE limits (nofile)"
    echo " 3) DNS helper (optional)"
    echo " 4) Enable swap (2G) (optional)"
    echo " 5) Show status"
    echo " 6) Rollback (latest backup)"
    echo " 7) Cleanup legacy risky tweaks (MTU/netplan/resolved)"
    echo " 0) Exit"
    echo "------------------------------------------------------------"
    read -r -p "Select: " c
    case "$c" in
      1) apply_sysctl_safe ;;
      2) apply_limits_safe ;;
      3) dns_menu ;;
      4) setup_swap_2g ;;
      5) show_status ;;
      6) rollback_latest ;;
      7) cleanup_legacy_risky ;;
      0) exit 0 ;;
      *) echo "Invalid." ;;
    esac
  done
}

main_menu
