# shellcheck shell=bash
# ============================================================================
# modules/dns.sh — DNS provider selection and safe application.
#
# Selection and application are deliberately decoupled: "Keep current DNS"
# really keeps it (the legacy v1 bug silently applied the default provider).
# No Domains=~. hijack; systemd-resolved gets a drop-in, plain systems get
# a tracked /etc/resolv.conf rewrite.
# ============================================================================

ST_DNS1=''
ST_DNS2=''

# Format: name|primary|secondary
readonly -a ST_DNS_PROVIDERS=(
  'Cloudflare|1.1.1.1|1.0.0.1'
  'Google|8.8.8.8|8.8.4.4'
  'Quad9|9.9.9.9|149.112.112.112'
  'OpenDNS|208.67.222.222|208.67.220.220'
  'Shecan (for Iran-hosted servers)|178.22.122.100|185.51.200.2'
)

# is_valid_ip — IPv4 strictly, IPv6 loosely (contains a colon, no spaces).
is_valid_ip() {
  is_valid_ipv4 "$1" || [[ $1 == *:* && $1 != *' '* && -n $1 ]]
}

dns_latency_test() {
  if ! has_cmd ping; then
    printf 'ping is not available on this system.\n'
    return 0
  fi
  local entry name ip1 ip2 ms
  printf '%sLatency to each provider (1 probe, 1s timeout):%s\n' "$C_MUTED" "$C_RESET"
  for entry in "${ST_DNS_PROVIDERS[@]}"; do
    IFS='|' read -r name ip1 ip2 <<<"$entry"
    ms="$(ping -c 1 -W 1 "$ip1" 2>/dev/null |
      awk -F'time=' '/time=/ {split($2, a, " "); print a[1]; exit}')" || ms=''
    if [[ -n $ms ]]; then
      printf '  %-34s %s ms\n' "$name" "$ms"
    else
      printf '  %-34s timeout\n' "$name"
    fi
  done
}

# dns_select_menu — sets ST_DNS1/ST_DNS2 and returns 0 when the user picked
# a provider to apply; returns 1 for "keep current" (caller MUST skip apply).
dns_select_menu() {
  local choice entry name ip1 ip2 i
  while true; do
    printf '\n%s[DNS provider]%s\n' "$C_TITLE" "$C_RESET"
    i=1
    for entry in "${ST_DNS_PROVIDERS[@]}"; do
      IFS='|' read -r name ip1 ip2 <<<"$entry"
      ui_menu_item "$i" "$name" "${ip1} / ${ip2}"
      i=$((i + 1))
    done
    ui_menu_item 6 "Custom" "enter your own (IPv4 or IPv6)"
    ui_menu_item t "Latency test" "ping every provider first"
    ui_menu_item 0 "Keep current DNS" "no DNS change"
    read -rp "Select [0]: " choice || return 1
    case "${choice:-0}" in
      [1-5])
        IFS='|' read -r name ST_DNS1 ST_DNS2 <<<"${ST_DNS_PROVIDERS[$((choice - 1))]}"
        return 0
        ;;
      6)
        read -rp "Primary DNS: " ST_DNS1 || return 1
        read -rp "Secondary DNS: " ST_DNS2 || return 1
        if is_valid_ip "$ST_DNS1" && is_valid_ip "$ST_DNS2"; then
          return 0
        fi
        printf '%sInvalid address — DNS left unchanged.%s\n' "$C_ERR" "$C_RESET"
        return 1
        ;;
      t | T) dns_latency_test ;;
      0) return 1 ;;
      *) printf '%sInvalid choice.%s\n' "$C_ERR" "$C_RESET" ;;
    esac
  done
}

# dns_resolve_cli VALUE — non-interactive parsing for --dns: a provider name
# (cloudflare|google|quad9|opendns|shecan) or "primary,secondary" addresses.
dns_resolve_cli() {
  local value="$1"
  case "${value,,}" in
    cloudflare)
      ST_DNS1='1.1.1.1'
      ST_DNS2='1.0.0.1'
      ;;
    google)
      ST_DNS1='8.8.8.8'
      ST_DNS2='8.8.4.4'
      ;;
    quad9)
      ST_DNS1='9.9.9.9'
      ST_DNS2='149.112.112.112'
      ;;
    opendns)
      ST_DNS1='208.67.222.222'
      ST_DNS2='208.67.220.220'
      ;;
    shecan)
      ST_DNS1='178.22.122.100'
      ST_DNS2='185.51.200.2'
      ;;
    *,*)
      ST_DNS1="${value%%,*}"
      ST_DNS2="${value#*,}"
      is_valid_ip "$ST_DNS1" && is_valid_ip "$ST_DNS2"
      ;;
    *) return 1 ;;
  esac
}

dns_apply() {
  [[ -n $ST_DNS1 && -n $ST_DNS2 ]] || return 2 # nothing selected — skip

  if has_cmd systemctl && systemctl is-active --quiet systemd-resolved 2>/dev/null; then
    local dropin='/etc/systemd/resolved.conf.d/99-server-tools.conf'
    st_track_file "$dropin"
    mkdir -p "$(dirname "$dropin")"
    cat >"$dropin" <<EOF
# Generated by ${ST_NAME} v${ST_VERSION}
[Resolve]
DNS=${ST_DNS1} ${ST_DNS2}
FallbackDNS=${ST_DNS2}
EOF
    if ! systemctl restart systemd-resolved 2>>"$ST_LOG_FILE"; then
      log_warn "systemd-resolved restart failed — drop-in written but not active yet."
      return 3
    fi
  else
    st_track_file /etc/resolv.conf
    if has_cmd chattr; then
      # Some providers lock resolv.conf with +i; unlock before writing.
      chattr -i /etc/resolv.conf 2>/dev/null || true
    fi
    rm -f /etc/resolv.conf
    cat >/etc/resolv.conf <<EOF
# Generated by ${ST_NAME} v${ST_VERSION}
nameserver ${ST_DNS1}
nameserver ${ST_DNS2}
EOF
    log_info "resolv.conf written directly (no systemd-resolved); note that a DHCP client may overwrite it."
  fi

  config_set dns_primary "$ST_DNS1"
  config_set dns_secondary "$ST_DNS2"
  log_info "DNS applied: ${ST_DNS1} / ${ST_DNS2}"
  return 0
}
