# shellcheck shell=bash
# ============================================================================
# modules/extras.sh — base-layer hygiene: journald disk cap and NTP sync.
# Small-disk VPSes fill up with journal logs; Reality/TLS handshakes need
# an accurate clock.
# ============================================================================

readonly ST_JOURNALD_DROPIN='/etc/systemd/journald.conf.d/99-server-tools.conf'

extras_apply() {
  local rc=0 did_anything=0

  if [[ -d /etc/systemd ]]; then
    st_track_file "$ST_JOURNALD_DROPIN"
    mkdir -p "$(dirname "$ST_JOURNALD_DROPIN")"
    cat >"$ST_JOURNALD_DROPIN" <<EOF
# Generated by ${ST_NAME} v${ST_VERSION}
[Journal]
SystemMaxUse=100M
RuntimeMaxUse=50M
EOF
    if has_cmd systemctl; then
      systemctl restart systemd-journald 2>>"$ST_LOG_FILE" ||
        log_warn "journald restart failed — the disk cap applies after next boot."
    fi
    did_anything=1
  fi

  if has_cmd timedatectl; then
    if ! timedatectl set-ntp true 2>>"$ST_LOG_FILE"; then
      log_warn "Could not enable NTP via timedatectl."
      rc=3
    fi
    did_anything=1
  fi

  ((did_anything)) || return 2
  return "$rc"
}
