# shellcheck shell=bash
# ============================================================================
# modules/ipv6.sh — optional, reversible full IPv6 disable.
#
# Some VPN stacks leak or lag over IPv6: happy-eyeballs races, half-configured
# SLAAC, or AAAA answers with no working v6 route. This switches the IPv6 stack
# off completely via a tracked sysctl drop-in — no reboot, no GRUB edit — undone
# by one Enable (or a normal rollback). It is deliberately NOT part of Quick
# Optimize: on a v6-only host it can cut network access, so it stays opt-in.
# ============================================================================

readonly ST_IPV6_SYSCTL='/etc/sysctl.d/99-server-tools-ipv6.conf'

# _ipv6_present — 0 when the kernel exposes the IPv6 stack at all (a kernel
# built or booted without IPv6 has no disable_ipv6 knob, so sysctl_get -> "?").
_ipv6_present() {
  [[ "$(sysctl_get net.ipv6.conf.all.disable_ipv6)" != '?' ]]
}

# _ipv6_disabled_live — 0 when the running kernel has IPv6 switched off.
_ipv6_disabled_live() {
  [[ "$(sysctl_get net.ipv6.conf.all.disable_ipv6)" == 1 ]]
}

# _ipv6_managed — 0 when ServerTools is the one that disabled IPv6 here.
_ipv6_managed() { [[ -f $ST_IPV6_SYSCTL ]]; }

# _ipv6_global_addrs — global-scope IPv6 addresses currently configured.
_ipv6_global_addrs() {
  has_cmd ip || return 0
  ip -6 addr show scope global 2>/dev/null | awk '/inet6 / {print $2}' || true
}

# _ipv6_ssh_is_v6 — 0 when THIS SSH session arrived over IPv6 (disabling would
# drop it). SSH_CONNECTION = "clientIP clientPort serverIP serverPort".
_ipv6_ssh_is_v6() {
  local srv
  [[ -n ${SSH_CONNECTION:-} ]] || return 1
  # SSH_CONNECTION is space-separated, but the tool's global IFS is $'\n\t'
  # (no space) — without an explicit space here every field lands empty.
  IFS=' ' read -r _ _ srv _ <<<"$SSH_CONNECTION"
  [[ $srv == *:* ]]
}

# _ipv6_v6_only — 0 when the host has no IPv4 default route but does have an
# IPv6 one: disabling IPv6 there would strand it off the network.
_ipv6_v6_only() {
  has_cmd ip || return 1
  local v4 v6
  v4="$(ip -4 route show default 2>/dev/null)" || v4=''
  v6="$(ip -6 route show default 2>/dev/null)" || v6=''
  [[ -z $v4 && -n $v6 ]]
}

ipv6_disable() {
  if ! _ipv6_present; then
    printf 'IPv6 is not present on this kernel (already fully disabled). Nothing to do.\n'
    return 0
  fi
  # Safety: never strand a host that reaches the network only over IPv6.
  if _ipv6_v6_only; then
    printf '%sRefusing:%s this host has no IPv4 default route but does have an IPv6\n' "$C_ERR" "$C_RESET"
    printf 'one — disabling IPv6 would cut it off the network. Nothing changed.\n'
    return 2
  fi

  printf 'This switches the IPv6 stack OFF completely on every interface; the\n'
  printf 'server keeps working over IPv4 only. It is reversible at any time.\n\n'
  printf '%sBefore you do this:%s\n' "$C_WARN" "$C_RESET"
  printf '  • A service listening on %s[::]%s (dual-stack) may need switching to\n' "$C_KEY" "$C_RESET"
  printf '    0.0.0.0, or it can fail to start after a reboot.\n'
  printf '  • Do not do this if your VPN actually serves IPv6 to clients.\n\n'

  if _ipv6_ssh_is_v6; then
    printf '%sWarning:%s your current SSH session is over IPv6 — it will drop the\n' "$C_ERR" "$C_RESET"
    printf 'moment IPv6 goes down. Reconnect over IPv4 first, or keep a console open.\n'
    ui_confirm "Continue disabling IPv6 anyway?" || return 2
  fi

  ui_confirm "Disable IPv6 completely now?" || return 2

  st_track_file "$ST_IPV6_SYSCTL"
  mkdir -p "$(dirname "$ST_IPV6_SYSCTL")"
  cat >"$ST_IPV6_SYSCTL" <<EOF
# Generated by ${ST_NAME} v${ST_VERSION} — full IPv6 disable.
# Reversible: Tools -> IPv6 control -> Enable, or delete this file and run
# 'sysctl --system'.
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
EOF

  if has_cmd sysctl; then
    sysctl -p "$ST_IPV6_SYSCTL" >/dev/null 2>>"$ST_LOG_FILE" ||
      log_warn "sysctl reported errors applying the IPv6 disable (see log)."
  else
    log_warn "sysctl not found — the setting is written but not applied live."
  fi

  if _ipv6_disabled_live; then
    local left
    left="$(_ipv6_global_addrs | paste -sd' ' -)" || left=''
    printf '\n%sIPv6 disabled%s on all interfaces (persists across reboots).\n' "$C_OK" "$C_RESET"
    [[ -n $left ]] &&
      printf '%sNote:%s a few addresses linger until services restart or a reboot: %s\n' \
        "$C_MUTED" "$C_RESET" "$left"
  else
    printf '\n%sIPv6 is still reported as enabled%s — see the log.\n' "$C_WARN" "$C_RESET"
  fi
  log_info "IPv6 disabled via ${ST_IPV6_SYSCTL}."
  return 0
}

ipv6_enable() {
  if [[ -f $ST_IPV6_SYSCTL ]]; then
    rm -f "$ST_IPV6_SYSCTL" || log_warn "Could not remove ${ST_IPV6_SYSCTL}."
  fi
  # The drop-in is gone, but the running values must be reset too, then a full
  # reload lets any other drop-in reassert its own intent.
  if has_cmd sysctl; then
    local k
    for k in all default lo; do
      sysctl -w "net.ipv6.conf.${k}.disable_ipv6=0" >/dev/null 2>>"$ST_LOG_FILE" ||
        log_warn "Could not re-enable IPv6 on '${k}' live."
    done
    sysctl --system >/dev/null 2>>"$ST_LOG_FILE" ||
      log_warn "sysctl --system reported errors during IPv6 re-enable (see log)."
  fi

  if _ipv6_disabled_live; then
    printf '%sIPv6 still shows disabled%s — a reboot will fully restore it.\n' "$C_WARN" "$C_RESET"
  else
    printf '%sIPv6 re-enabled.%s Interfaces reacquire addresses via RA/DHCPv6.\n' "$C_OK" "$C_RESET"
  fi
  log_info "IPv6 re-enabled (drop-in removed)."
  return 0
}

# ipv6_verify — doctor contract: 0 in effect, 2 not configured, 3 drift.
ipv6_verify() {
  _ipv6_managed || return 2
  _ipv6_disabled_live && return 0
  return 3
}

# ipv6_control — the interactive screen: show state, then disable or enable.
ipv6_control() {
  ui_section "IPv6 control"
  printf 'IPv6 can cause connection races, leaks or lag on some VPN setups. Here\n'
  printf 'you can switch the whole IPv6 stack off (IPv4 keeps working) or back on\n'
  printf '— reversible, no reboot.\n'

  local state addrs
  if ! _ipv6_present; then
    state='not present (kernel-level off)'
  elif _ipv6_disabled_live; then
    if _ipv6_managed; then
      state='disabled (by ServerTools)'
    else
      state='disabled (outside ServerTools)'
    fi
  else
    state='enabled'
  fi
  addrs="$(_ipv6_global_addrs | paste -sd' ' -)" || addrs=''

  printf '\n'
  ui_kv "IPv6 stack" "$state"
  ui_kv "Global addresses" "${addrs:-none}"
  printf '\n'

  if ! _ipv6_present; then
    printf 'Nothing to manage — this kernel has no IPv6 stack.\n'
  elif _ipv6_managed; then
    if ui_confirm "Re-enable IPv6 now?"; then ipv6_enable; fi
  elif _ipv6_disabled_live; then
    printf 'IPv6 is already disabled here (not by ServerTools) — left unchanged.\n'
  else
    ipv6_disable
  fi
  return 0
}
