# shellcheck shell=bash
# ============================================================================
# modules/limits.sh — file-descriptor limits for 100k+ concurrent sockets.
# Uses a systemd drop-in instead of sed-editing system.conf, so rollback is
# a clean file removal (legacy v1 mutated /etc/systemd/system.conf in place).
# ============================================================================

readonly ST_LIMITS_FILE='/etc/security/limits.d/99-server-tools.conf'
readonly ST_SYSTEMD_DROPIN='/etc/systemd/system.conf.d/99-server-tools.conf'

limits_apply() {
  st_track_file "$ST_LIMITS_FILE"
  mkdir -p "$(dirname "$ST_LIMITS_FILE")"
  cat >"$ST_LIMITS_FILE" <<EOF
# Generated by ${ST_NAME} v${ST_VERSION}
* soft nofile 1048576
* hard nofile 1048576
root soft nofile 1048576
root hard nofile 1048576
EOF

  if [[ -d /etc/systemd ]]; then
    st_track_file "$ST_SYSTEMD_DROPIN"
    mkdir -p "$(dirname "$ST_SYSTEMD_DROPIN")"
    cat >"$ST_SYSTEMD_DROPIN" <<EOF
# Generated by ${ST_NAME} v${ST_VERSION}
[Manager]
DefaultLimitNOFILE=1048576
EOF
    if has_cmd systemctl && ! systemctl daemon-reexec 2>>"$ST_LOG_FILE"; then
      log_warn "systemd daemon-reexec failed — new limits take effect after reboot."
      return 3
    fi
  fi

  log_info "nofile limits set to 1048576 (PAM + systemd drop-in)."
  return 0
}
