# shellcheck shell=bash
# ============================================================================
# modules/perf.sh — CPU/NIC data-path tuning that lives in /sys, not sysctl.
#
# Three wins that /etc/sysctl.d cannot express, all zero-footprint:
#   - RPS/RFS/XPS: spread NIC softirq processing across every core. Decisive
#     on the single-queue virtio NICs most VPS ship — one core otherwise caps
#     the whole node's packet rate. Skipped when the NIC already has as many
#     hardware queues as cores (RSS already spreads the load).
#   - CPU governor = performance: no ramp-up latency on bursty proxy traffic.
#     Silently skipped where cpufreq is absent (typical virtualised host).
#   - Transparent Huge Pages = madvise: stops khugepaged compaction stalls
#     from adding tail-latency spikes, without denying THP to code that asks.
#
# These settings do not survive a reboot on their own, so they are persisted
# through ONE oneshot systemd unit that runs a generated, idempotent boot
# script and exits — no resident process (CLAUDE.md rule 1). NIC ring/coalesce
# tuning (ethtool -G) is deliberately excluded: it can reset the link and
# harms latency on many hypervisors (see docs/SYSCTL.md "Deliberately NOT set").
# ============================================================================

readonly ST_PERF_BOOT='/etc/server-tools/perf-boot.sh'
readonly ST_PERF_UNIT='/etc/systemd/system/server-tools-perf.service'

# _perf_cpu_mask CORES — the kernel rps_cpus/xps_cpus bitmask covering CORES
# online CPUs: comma-separated 32-bit hex words, most-significant first
# (e.g. 4 -> "0000000f", 40 -> "000000ff,ffffffff"). Capped at 64 cores.
_perf_cpu_mask() {
  local cores="$1"
  ((cores > 64)) && cores=64
  # Two-step arithmetic throughout: nested parens inside $(( )) get normalised
  # to a triple-paren form that ShellCheck then misreads as $( (subshell) ).
  local i bits word mask='' groups
  groups=$((cores + 31))
  groups=$((groups / 32))
  for ((i = groups - 1; i >= 0; i--)); do
    bits=$((cores - i * 32))
    ((bits > 32)) && bits=32
    if ((bits >= 32)); then
      word=4294967295 # 0xffffffff — a full 32-bit group
    else
      word=$((1 << bits))
      word=$((word - 1))
    fi
    mask+="$(printf '%08x' "$word")"
    ((i > 0)) && mask+=','
  done
  printf '%s' "$mask"
}

# _perf_rps_beneficial IFACE CORES — RPS helps only when the NIC spreads
# traffic across fewer hardware queues than we have cores to steer it onto.
_perf_rps_beneficial() {
  local iface="$1" cores="$2" mode nq
  mode="$(config_get rps_mode auto)"
  case "$mode" in
    on) return 0 ;;
    off) return 1 ;;
  esac
  ((cores > 1)) || return 1
  [[ -n $iface && -d /sys/class/net/$iface/queues ]] || return 1
  nq="$(find "/sys/class/net/${iface}/queues" -maxdepth 1 -name 'rx-*' -type d 2>/dev/null | wc -l)"
  [[ $nq =~ ^[0-9]+$ ]] || return 1
  ((nq < cores))
}

# _perf_plan IFACE MASK — emit "path<TAB>value" for every /sys tweak that
# applies on THIS host. Single source of truth for both live-apply and the
# persisted boot script; only writable targets are listed.
_perf_plan() {
  local iface="$1" mask="$2" g q
  for g in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
    [[ -w $g ]] && printf '%s\t%s\n' "$g" performance
  done
  [[ -w /sys/kernel/mm/transparent_hugepage/enabled ]] &&
    printf '%s\t%s\n' /sys/kernel/mm/transparent_hugepage/enabled madvise
  [[ -w /sys/kernel/mm/transparent_hugepage/defrag ]] &&
    printf '%s\t%s\n' /sys/kernel/mm/transparent_hugepage/defrag madvise
  if [[ -n $iface && -n $mask ]]; then
    # RFS global flow table; per-queue counts complete the RFS hash.
    [[ -w /proc/sys/net/core/rps_sock_flow_entries ]] &&
      printf '%s\t%s\n' /proc/sys/net/core/rps_sock_flow_entries 32768
    for q in /sys/class/net/"$iface"/queues/rx-*; do
      [[ -w $q/rps_cpus ]] && printf '%s\t%s\n' "$q/rps_cpus" "$mask"
      [[ -w $q/rps_flow_cnt ]] && printf '%s\t%s\n' "$q/rps_flow_cnt" 4096
    done
    for q in /sys/class/net/"$iface"/queues/tx-*; do
      [[ -w $q/xps_cpus ]] && printf '%s\t%s\n' "$q/xps_cpus" "$mask"
    done
  fi
}

# _perf_write_boot PLAN — a self-contained, idempotent boot script (each write
# tolerant) plus the oneshot unit that runs it. Both are tracked for rollback.
_perf_write_boot() {
  local plan="$1" path value
  st_track_file "$ST_PERF_BOOT"
  mkdir -p "$(dirname "$ST_PERF_BOOT")"
  {
    printf '#!/usr/bin/env bash\n'
    printf '# Generated by %s v%s — reapplies non-persistent /sys tuning at boot.\n' "$ST_NAME" "$ST_VERSION"
    printf '# RPS/RFS/XPS, CPU governor, THP. Idempotent; safe to run repeatedly.\n'
    printf 'set -u\n'
    while IFS=$'\t' read -r path value; do
      [[ -n $path ]] || continue
      printf 'printf %%s %s > %s 2>/dev/null || true\n' "$value" "$path"
    done <<<"$plan"
  } >"$ST_PERF_BOOT"
  chmod 0755 "$ST_PERF_BOOT"

  st_track_file "$ST_PERF_UNIT"
  mkdir -p "$(dirname "$ST_PERF_UNIT")"
  {
    printf '# Generated by %s v%s\n' "$ST_NAME" "$ST_VERSION"
    printf '[Unit]\nDescription=ServerTools CPU/NIC performance tuning (oneshot, exits after boot)\n'
    printf 'After=network-online.target\nWants=network-online.target\n\n'
    printf '[Service]\nType=oneshot\nRemainAfterExit=yes\n'
    printf 'ExecStart=%s\n' "$ST_PERF_BOOT"
    printf '\n[Install]\nWantedBy=multi-user.target\n'
  } >"$ST_PERF_UNIT"
}

# perf_apply — Quick/Custom Optimize step. 0=applied, 2=nothing applicable,
# 3=applied but some targets were read-only.
perf_apply() {
  local cores iface mask='' rps=0
  cores="$(cpu_cores)"
  [[ $cores =~ ^[0-9]+$ ]] || cores=1
  iface="$(net_default_iface)" || iface=''
  if _perf_rps_beneficial "$iface" "$cores"; then
    mask="$(_perf_cpu_mask "$cores")"
    rps=1
  fi

  local plan
  plan="$(_perf_plan "$iface" "$mask")"
  if [[ -z $plan ]]; then
    log_info "perf: nothing applicable (no cpufreq, THP or RPS on this host)."
    return 2
  fi

  local path value applied=0 unavail=0
  while IFS=$'\t' read -r path value; do
    [[ -n $path ]] || continue
    if printf '%s\n' "$value" >"$path" 2>>"$ST_LOG_FILE"; then
      applied=$((applied + 1))
    else
      unavail=$((unavail + 1))
    fi
  done <<<"$plan"

  local rc=0
  if [[ -d /etc/systemd/system ]] && has_cmd systemctl; then
    _perf_write_boot "$plan"
    systemctl daemon-reload 2>>"$ST_LOG_FILE" || log_warn "daemon-reload failed."
    if systemctl enable server-tools-perf.service >/dev/null 2>>"$ST_LOG_FILE"; then
      manifest_add unit server-tools-perf.service
    else
      log_warn "Could not enable boot persistence for the performance tuning."
      rc=3
    fi
  else
    log_warn "No systemd — performance tuning is active now but will not survive a reboot."
    rc=3
  fi

  if ((rps)); then
    log_note "RPS/RFS/XPS spread across ${cores} core(s) on ${iface} (single/low-queue NIC)."
  elif [[ -n $iface ]]; then
    log_note "RPS skipped — ${iface} already has enough hardware queues."
  fi
  if ((unavail > 0)); then
    log_note "${unavail} target(s) were read-only and left as-is."
    ((rc == 0)) && rc=3
  fi

  log_info "perf applied: applied=${applied} unavail=${unavail} rps=${rps} cores=${cores} iface=${iface:-none}."
  return "$rc"
}

# perf_verify — 0 when every setting the boot script manages is still live,
# 3 on drift, 2 when performance tuning was never configured here.
perf_verify() {
  [[ -f $ST_PERF_BOOT ]] || return 2
  local line value path cur drift=0
  while IFS= read -r line; do
    [[ $line == printf* ]] || continue
    # printf %s VALUE > PATH 2>/dev/null || true
    value="$(awk '{print $3}' <<<"$line")"
    path="$(awk '{print $5}' <<<"$line")"
    [[ -n $path && -r $path ]] || continue
    cur="$(cat "$path" 2>/dev/null)" || continue
    case "$path" in
      *transparent_hugepage*)
        [[ $cur == *"[$value]"* ]] || drift=1
        ;;
      *rps_cpus | *xps_cpus)
        # The kernel reformats the mask; a non-zero read means RPS is active.
        [[ -n ${cur//[,0]/} ]] || drift=1
        ;;
      *)
        [[ $cur == "$value" ]] || drift=1
        ;;
    esac
  done <"$ST_PERF_BOOT"
  ((drift)) && return 3
  return 0
}
