# shellcheck shell=bash
# ============================================================================
# modules/security.sh — Layer 3 optional hardening: UFW, fail2ban, SSH.
#
# Everything here is consent-based (CLAUDE.md rule 1). fail2ban is the only
# resident service in the whole project and its cost is stated before the
# user agrees. The SSH allow rule always lands before any deny rule, and the
# sshd drop-in is validated with `sshd -t` before restart — no lockouts.
# ============================================================================

readonly ST_F2B_JAIL='/etc/fail2ban/jail.d/99-server-tools.local'
readonly ST_SSHD_DROPIN='/etc/ssh/sshd_config.d/99-server-tools.conf'

detect_ssh_port() {
  local port=''
  port="$(awk '/^[[:space:]]*[Pp]ort[[:space:]]/ {print $2; exit}' /etc/ssh/sshd_config 2>/dev/null)" || port=''
  if [[ -z $port ]] && has_cmd ss; then
    port="$(ss -tnlp 2>/dev/null | awk '/sshd/ {sub(/.*:/, "", $4); print $4; exit}')" || port=''
  fi
  [[ $port =~ ^[0-9]+$ ]] || port=22
  printf '%s' "$port"
}

security_ufw() {
  ui_section "UFW firewall"
  if ! has_cmd ufw; then
    ui_confirm "UFW is not installed. Install it now?" || return 0
    if ! pkg_install ufw; then
      log_error "UFW installation failed — see the log."
      return 0
    fi
  fi

  local ssh_port
  ssh_port="$(detect_ssh_port)"
  printf 'Detected SSH port: %s — it is allowed FIRST, so you cannot be locked out.\n' "$ssh_port"
  if ! ufw allow "${ssh_port}/tcp" >/dev/null 2>>"$ST_LOG_FILE"; then
    log_error "Could not add the SSH allow rule — aborting before any deny rule."
    return 0
  fi
  ufw default deny incoming >/dev/null 2>>"$ST_LOG_FILE" || log_warn "Could not set default deny incoming."
  ufw default allow outgoing >/dev/null 2>>"$ST_LOG_FILE" || log_warn "Could not set default allow outgoing."

  local ports p
  read -rp "Extra ports to allow (e.g. 443/tcp 80/tcp 51820/udp) [Enter=none]: " ports || ports=''
  if [[ -n $ports ]]; then
    local IFS=' ' # the global IFS has no space — restore word splitting here
    for p in $ports; do
      if [[ $p =~ ^[0-9]+(/(tcp|udp))?$ ]]; then
        ufw allow "$p" >/dev/null 2>>"$ST_LOG_FILE" || log_warn "Rule failed: ${p}"
      else
        log_warn "Skipped invalid port spec: ${p}"
      fi
    done
  fi

  if has_cmd docker && docker ps -q 2>/dev/null | grep -q .; then
    printf '%sWarning:%s Docker publishes container ports directly in iptables and\n' "$C_WARN" "$C_RESET"
    printf 'BYPASSES UFW — published panel/node ports stay reachable regardless of\n'
    printf 'these rules (see Network tools > Docker+UFW audit).\n'
  fi

  if ui_confirm "Enable UFW now?"; then
    if ufw --force enable >/dev/null 2>>"$ST_LOG_FILE"; then
      printf '%sUFW enabled.%s\n' "$C_OK" "$C_RESET"
      ufw status verbose 2>/dev/null || log_warn "Could not print UFW status."
    else
      log_error "Enabling UFW failed — see the log."
      return 0
    fi
  fi
  printf '%sNote:%s firewall state is not covered by manifest rollback — revert with: ufw disable\n' \
    "$C_MUTED" "$C_RESET"
  log_info "UFW configured (SSH ${ssh_port}/tcp allowed)."
}

security_fail2ban() {
  ui_section "fail2ban (SSH brute-force protection)"
  printf 'fail2ban runs as a small resident service (~20 MB RAM) — the only\n'
  printf 'exception to the zero-footprint rule, and only with your consent.\n'
  ui_confirm "Install and enable fail2ban?" || return 0

  if ! has_cmd fail2ban-server && ! pkg_install fail2ban; then
    log_error "fail2ban installation failed — see the log."
    return 0
  fi

  local ssh_port
  ssh_port="$(detect_ssh_port)"
  st_track_file "$ST_F2B_JAIL"
  mkdir -p "$(dirname "$ST_F2B_JAIL")"
  cat >"$ST_F2B_JAIL" <<EOF
# Generated by ${ST_NAME} v${ST_VERSION}
[sshd]
enabled = true
port = ${ssh_port}
backend = systemd
maxretry = 5
findtime = 10m
bantime = 1h
EOF

  if has_cmd systemctl &&
    systemctl enable fail2ban >/dev/null 2>>"$ST_LOG_FILE" &&
    systemctl restart fail2ban 2>>"$ST_LOG_FILE"; then
    printf '%sfail2ban active%s (sshd jail on port %s, ban 1h after 5 tries).\n' \
      "$C_OK" "$C_RESET" "$ssh_port"
    log_info "fail2ban enabled (sshd jail, port ${ssh_port})."
  else
    log_error "fail2ban could not be enabled — see the log."
  fi
}

security_ssh() {
  ui_section "SSH hardening"
  if [[ ! -d /etc/ssh/sshd_config.d ]]; then
    log_warn "This system has no /etc/ssh/sshd_config.d — skipping (editing sshd_config in place is not safe enough)."
    return 0
  fi

  local lines=('UseDNS no')
  if [[ -s /root/.ssh/authorized_keys ]]; then
    printf 'An SSH key for root exists.\n'
    printf '%sVerify key login works in a second terminal BEFORE confirming.%s\n' "$C_WARN" "$C_RESET"
    if ui_confirm "Disable password authentication?"; then
      lines+=('PasswordAuthentication no')
    fi
  else
    printf '%sNo /root/.ssh/authorized_keys found — password login stays enabled.%s\n' "$C_WARN" "$C_RESET"
  fi

  st_track_file "$ST_SSHD_DROPIN"
  {
    printf '# Generated by %s v%s\n' "$ST_NAME" "$ST_VERSION"
    printf '%s\n' "${lines[@]}"
  } >"$ST_SSHD_DROPIN"

  if has_cmd sshd && ! sshd -t 2>>"$ST_LOG_FILE"; then
    rm -f "$ST_SSHD_DROPIN"
    log_error "sshd config validation failed — drop-in removed, nothing changed."
    return 0
  fi
  if has_cmd systemctl; then
    # Service name differs across distros (ssh on Debian/Ubuntu, sshd elsewhere).
    systemctl restart ssh 2>/dev/null || systemctl restart sshd 2>>"$ST_LOG_FILE" ||
      log_warn "Could not restart sshd — settings apply on its next restart."
  fi
  printf '%sApplied:%s %s\n' "$C_OK" "$C_RESET" "${lines[*]}"
  log_info "SSH hardening drop-in applied: ${lines[*]}"
}

security_menu() {
  local choice
  while true; do
    ui_logo
    ui_title "Security (Layer 3 — optional, consent-based)"
    ui_menu_item 1 "UFW firewall" "SSH-safe setup, extra ports, Docker warning"
    ui_menu_item 2 "fail2ban" "SSH brute-force bans (resident service ~20 MB)"
    ui_menu_item 3 "SSH hardening" "UseDNS off, optional key-only login (validated)"
    ui_menu_item 0 "Back"
    ui_hr
    read -rp "Select: " choice || return 0
    case "${choice:-}" in
      1)
        security_ufw
        ui_pause
        ;;
      2)
        security_fail2ban
        ui_pause
        ;;
      3)
        security_ssh
        ui_pause
        ;;
      0) return 0 ;;
      *)
        printf '%sInvalid choice.%s\n' "$C_ERR" "$C_RESET"
        sleep 1
        ;;
    esac
  done
}
