# shellcheck shell=bash
# ============================================================================
# modules/swap.sh — swap provisioning when no swap exists at all.
#
# Backends (config key swap_backend = auto | file | zram):
#   file — swap file on disk: real extra capacity, the universal safe default.
#   zram — compressed in-RAM swap: no disk needed, much faster than slow VPS
#          disks, but adds no capacity beyond RAM itself.
#   auto — file first (best scenario for most servers); falls back to zram
#          automatically when the disk is too small for a swap file.
#
# The fstab entry / boot unit is only written AFTER swapon verifiably works.
# ============================================================================

readonly ST_ZRAM_UNIT='/etc/systemd/system/server-tools-zram.service'

swap_is_active() {
  [[ -r /proc/swaps ]] && awk 'NR > 1 {found = 1} END {exit !found}' /proc/swaps
}

# _swap_file_setup SIZE_MB
_swap_file_setup() {
  local size_mb="$1" swapfile='/swapfile' fstype
  st_track_file /etc/fstab
  st_track_file "$swapfile" # recorded as "created" so rollback removes it

  fstype="$(stat -f -c %T / 2>/dev/null)" || fstype=''
  if [[ $fstype == btrfs ]]; then
    # CoW must be disabled on the empty file before any data is written, and
    # fallocate'd files are not usable as swap on btrfs — always use dd.
    touch "$swapfile"
    if has_cmd chattr; then
      chattr +C "$swapfile" 2>/dev/null || true # best effort; swapon verifies below
    fi
    dd if=/dev/zero of="$swapfile" bs=1M count="$size_mb" status=none 2>>"$ST_LOG_FILE" || return 1
  else
    if ! fallocate -l "${size_mb}M" "$swapfile" 2>/dev/null; then
      dd if=/dev/zero of="$swapfile" bs=1M count="$size_mb" status=none 2>>"$ST_LOG_FILE" || return 1
    fi
  fi

  chmod 600 "$swapfile"
  mkswap "$swapfile" >/dev/null 2>>"$ST_LOG_FILE" || return 1
  if ! swapon "$swapfile" 2>>"$ST_LOG_FILE"; then
    log_error "swapon failed (filesystem: ${fstype:-unknown}) — swap file removed, fstab untouched."
    rm -f "$swapfile"
    return 1
  fi

  if ! grep -qE '^[[:space:]]*/swapfile[[:space:]]' /etc/fstab 2>/dev/null; then
    printf '/swapfile none swap sw 0 0\n' >>/etc/fstab
  fi
  log_info "Swap file enabled: ${size_mb} MB (fs: ${fstype:-unknown})."
  return 0
}

# _swap_zram_setup SIZE_MB — compressed swap in RAM, priority above any
# future disk swap. Boot persistence via a oneshot unit (nothing resident).
_swap_zram_setup() {
  local size_mb="$1"
  ((size_mb < 256)) && size_mb=256
  ((size_mb > 4096)) && size_mb=4096

  if ! modprobe zram 2>>"$ST_LOG_FILE" || [[ ! -b /dev/zram0 ]]; then
    log_error "zram kernel module unavailable on this system."
    return 1
  fi
  # lz4 beats the default algorithm on weak vCPUs; not fatal when missing.
  echo lz4 >/sys/block/zram0/comp_algorithm 2>/dev/null || true
  if ! echo "${size_mb}M" >/sys/block/zram0/disksize 2>>"$ST_LOG_FILE"; then
    log_error "Could not size /dev/zram0."
    return 1
  fi
  mkswap /dev/zram0 >/dev/null 2>>"$ST_LOG_FILE" || return 1
  if ! swapon -p 100 /dev/zram0 2>>"$ST_LOG_FILE"; then
    log_error "swapon on /dev/zram0 failed."
    return 1
  fi

  if [[ -d /etc/systemd/system ]] && has_cmd systemctl; then
    st_track_file "$ST_ZRAM_UNIT"
    cat >"$ST_ZRAM_UNIT" <<EOF
# Generated by ${ST_NAME} v${ST_VERSION}
[Unit]
Description=ServerTools zram swap (oneshot, exits after boot)

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/bash -c 'modprobe zram && { echo lz4 > /sys/block/zram0/comp_algorithm 2>/dev/null; true; } && echo ${size_mb}M > /sys/block/zram0/disksize && mkswap /dev/zram0 && swapon -p 100 /dev/zram0'
ExecStop=/bin/bash -c 'swapoff /dev/zram0 && echo 1 > /sys/block/zram0/reset'

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload 2>>"$ST_LOG_FILE" || log_warn "daemon-reload failed."
    if systemctl enable server-tools-zram.service >/dev/null 2>>"$ST_LOG_FILE"; then
      manifest_add unit server-tools-zram.service
    else
      log_warn "Could not enable zram boot persistence — active now, gone after reboot."
    fi
  else
    log_warn "No systemd — zram swap is active now but will not survive a reboot."
  fi

  log_info "zram swap enabled: ${size_mb} MB compressed (priority 100)."
  return 0
}

swap_apply() {
  if swap_is_active; then
    log_info "Swap already active — skipped."
    return 2
  fi

  local backend size_mb ram_mb avail_mb disk_ok=0
  backend="$(config_get swap_backend auto)"
  size_mb="$(config_get swap_size_mb 2048)"
  [[ $size_mb =~ ^[0-9]+$ ]] || size_mb=2048
  ram_mb="$(mem_total_mb)"

  # Disk headroom check: swap size + 1 GB safety margin.
  avail_mb="$(df -Pm / 2>/dev/null | awk 'NR == 2 {print $4}')" || avail_mb=0
  [[ $avail_mb =~ ^[0-9]+$ ]] || avail_mb=0
  ((avail_mb >= size_mb + 1024)) && disk_ok=1

  case "$backend" in
    file)
      if ((disk_ok == 0)); then
        log_error "Not enough free disk for a ${size_mb} MB swap file (available: ${avail_mb} MB)."
        return 1
      fi
      _swap_file_setup "$size_mb"
      ;;
    zram)
      _swap_zram_setup "$((ram_mb / 2))"
      ;;
    *) # auto — real disk capacity first, compressed RAM as the fallback.
      if ((disk_ok)); then
        _swap_file_setup "$size_mb"
      else
        log_warn "Disk too small for a swap file — using zram (compressed RAM) instead."
        _swap_zram_setup "$((ram_mb / 2))"
      fi
      ;;
  esac
}
