# shellcheck shell=bash
# ============================================================================
# modules/sysctl.sh — kernel network tuning. Implements docs/SYSCTL.md
# exactly: Layer 1 (base) always, Layer 2 forwarding keys for VPN profiles.
# Every written file is tracked via st_track_file for rollback.
# ============================================================================

readonly ST_SYSCTL_FILE='/etc/sysctl.d/99-server-tools.conf'
readonly ST_MODULES_FILE='/etc/modules-load.d/server-tools.conf'
readonly ST_MODPROBE_FILE='/etc/modprobe.d/server-tools.conf'

ST_CC='cubic'
ST_QDISC='fq_codel'

sysctl_detect_bbr() {
  ST_CC='cubic'
  ST_QDISC='fq_codel'
  ver_ge "$(kernel_base)" "4.9" || return 0
  # Kernels with built-in BBR have no module to load; availability is
  # verified against the actual sysctl list right after.
  modprobe tcp_bbr 2>/dev/null || true
  if [[ " $(sysctl_get net.ipv4.tcp_available_congestion_control) " == *bbr* ]]; then
    ST_CC='bbr'
    ST_QDISC='fq'
  fi
  return 0
}

# _sysctl_reserved_ports — listening ports that sit inside our ephemeral
# range (10240-65535), comma-joined for ip_local_reserved_ports. Capped via
# awk (head would SIGPIPE the producer under pipefail).
_sysctl_reserved_ports() {
  has_cmd ss || return 0
  ss -tuln 2>/dev/null |
    awk 'NR > 1 {sub(/.*:/, "", $5); if ($5 ~ /^[0-9]+$/ && $5 >= 10240 && $5 <= 65535) print $5}' |
    sort -un | awk 'NR <= 32' | paste -sd, -
}

_sysctl_render() {
  local buf_bytes=$((ST_BUF_MB * 1048576))
  local ram_mb ram_pages
  ram_mb="$(mem_total_mb)"
  ram_pages=$((ram_mb * 256)) # 4 KiB pages

  cat <<EOF
# Generated by ${ST_NAME} v${ST_VERSION} (profile=${ST_PROFILE}, tier=${ST_TIER})
# The rationale for every key lives in docs/SYSCTL.md:
# ${ST_REPO_URL}

# --- Congestion control & queueing
net.core.default_qdisc = ${ST_QDISC}
net.ipv4.tcp_congestion_control = ${ST_CC}

# --- Connection accept path (tier ${ST_TIER})
net.core.somaxconn = ${ST_SOMAXCONN}
net.ipv4.tcp_max_syn_backlog = ${ST_SOMAXCONN}
net.core.netdev_max_backlog = ${ST_NETDEV_BACKLOG}
net.ipv4.tcp_syncookies = 1

# --- Ports, timers, keepalive
net.ipv4.ip_local_port_range = 10240 65535
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_keepalive_time = 300
net.ipv4.tcp_keepalive_intvl = 60
net.ipv4.tcp_keepalive_probes = 5
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_no_metrics_save = 1
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_notsent_lowat = 16384
# Protect TIME-WAIT sockets from RST assassination (RFC 1337).
net.ipv4.tcp_rfc1337 = 1
# Mode 1 probes only after a blackhole is detected (mode 2 is the harmful one).
net.ipv4.tcp_mtu_probing = 1

# --- Buffers (tier ${ST_TIER})
net.core.rmem_max = ${buf_bytes}
net.core.wmem_max = ${buf_bytes}
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.ipv4.tcp_rmem = 4096 87380 ${buf_bytes}
net.ipv4.tcp_wmem = 4096 65536 ${buf_bytes}
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
net.ipv4.udp_mem = $((ram_pages / 32)) $((ram_pages / 16)) $((ram_pages / 8))
net.core.optmem_max = 65536

# --- System capacity
fs.file-max = 2097152
vm.swappiness = 10
EOF

  # High-churn caps only where the connection volume justifies them.
  if [[ $ST_TIER == L || $ST_TIER == XL ]]; then
    local tw_buckets=524288 max_orphans=131072
    if [[ $ST_TIER == XL ]]; then
      tw_buckets=1048576
      max_orphans=262144
    fi
    cat <<EOF

# --- High-churn caps (tier ${ST_TIER})
net.ipv4.tcp_max_tw_buckets = ${tw_buckets}
net.ipv4.tcp_max_orphans = ${max_orphans}
EOF
  fi

  # Keep detected service ports out of the ephemeral source-port pool so an
  # outgoing connection can never collide with a panel/node listener.
  local reserved
  reserved="$(_sysctl_reserved_ports)" || reserved=''
  if [[ -n $reserved ]]; then
    cat <<EOF

# --- Listening ports inside the ephemeral range, reserved automatically
net.ipv4.ip_local_reserved_ports = ${reserved}
EOF
  fi

  if profile_wants_forwarding; then
    cat <<EOF

# --- VPN workload (profile ${ST_PROFILE}): routing + conntrack + hardening
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
net.netfilter.nf_conntrack_max = ${ST_CONNTRACK}
# Kernel default is 5 DAYS — idle VPN flows would exhaust the table.
net.netfilter.nf_conntrack_tcp_timeout_established = 3600
net.ipv4.conf.all.rp_filter = 2
net.ipv4.conf.default.rp_filter = 2
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
EOF
  fi
}

# sysctl_dry_run — render the exact config this run would write and diff
# every key against the live kernel. Applies NOTHING and tracks nothing.
sysctl_dry_run() {
  sysctl_detect_bbr
  local rendered line key value current changed=0 total=0
  rendered="$(_sysctl_render)"

  printf '%s[Rendered %s]%s\n%s\n\n' "$C_TITLE" "$ST_SYSCTL_FILE" "$C_RESET" "$rendered"
  printf '%s[Diff vs live kernel]%s\n' "$C_TITLE" "$C_RESET"
  while IFS= read -r line; do
    [[ -z $line || $line == \#* ]] && continue
    key="${line%%=*}"
    key="${key//[[:space:]]/}"
    value="${line#*=}"
    value="${value#"${value%%[![:space:]]*}"}"
    current="$(sysctl_get "$key")"
    total=$((total + 1))
    # Normalize runs of whitespace so multi-value keys compare fairly.
    if [[ "$(tr -s ' \t' ' ' <<<"$current")" != "$(tr -s ' \t' ' ' <<<"$value")" ]]; then
      printf '  %s%-50s%s %s -> %s\n' "$C_KEY" "$key" "$C_RESET" "${current}" "${value}"
      changed=$((changed + 1))
    fi
  done <<<"$rendered"

  ((changed == 0)) && printf '  (kernel already matches this profile)\n'
  printf '\n%s%d of %d keys would change. Nothing was applied.%s\n' \
    "$C_WARN" "$changed" "$total" "$C_RESET"
}

sysctl_apply() {
  if ! has_cmd sysctl; then
    log_error "sysctl command not found — cannot tune the kernel."
    return 1
  fi

  sysctl_detect_bbr

  local modules=()
  [[ $ST_CC == bbr ]] && modules+=(tcp_bbr)

  if profile_wants_forwarding; then
    # Without the module loaded, net.netfilter.* keys silently fail to apply.
    modprobe nf_conntrack 2>/dev/null ||
      log_warn "nf_conntrack module unavailable — conntrack keys may not apply."
    modules+=(nf_conntrack)
  fi

  st_track_file "$ST_SYSCTL_FILE"
  mkdir -p "$(dirname "$ST_SYSCTL_FILE")"
  _sysctl_render >"$ST_SYSCTL_FILE"

  if ((${#modules[@]} > 0)); then
    st_track_file "$ST_MODULES_FILE"
    mkdir -p "$(dirname "$ST_MODULES_FILE")"
    {
      printf '# Generated by %s v%s\n' "$ST_NAME" "$ST_VERSION"
      printf '%s\n' "${modules[@]}"
    } >"$ST_MODULES_FILE"
  fi

  if profile_wants_forwarding; then
    # The conntrack hash table must scale with the table itself; the runtime
    # knob is a module parameter, persisted for reboots via modprobe.d.
    local hashsize=$((ST_CONNTRACK / 4))
    st_track_file "$ST_MODPROBE_FILE"
    mkdir -p "$(dirname "$ST_MODPROBE_FILE")"
    printf '# Generated by %s v%s\noptions nf_conntrack hashsize=%s\n' \
      "$ST_NAME" "$ST_VERSION" "$hashsize" >"$ST_MODPROBE_FILE"
    if [[ -w /sys/module/nf_conntrack/parameters/hashsize ]]; then
      printf '%s' "$hashsize" >/sys/module/nf_conntrack/parameters/hashsize 2>>"$ST_LOG_FILE" ||
        log_warn "Could not resize the conntrack hash table live (persisted for next boot)."
    fi
  fi

  # Apply; per-key errors land in the log instead of vanishing — the keys we
  # care about are verified individually right after.
  sysctl --system >/dev/null 2>>"$ST_LOG_FILE" || true

  # default_qdisc only affects NEW interfaces; switch the live default
  # interface too so the change is complete without a reboot.
  local iface
  iface="$(net_default_iface)" || iface=''
  if [[ -n $iface ]] && has_cmd tc; then
    tc qdisc replace dev "$iface" root "$ST_QDISC" 2>>"$ST_LOG_FILE" ||
      log_warn "Could not switch ${iface} to ${ST_QDISC} live (it applies after reboot)."
  fi

  local cc_now qdisc_now rc=0
  cc_now="$(sysctl_get net.ipv4.tcp_congestion_control)"
  qdisc_now="$(sysctl_get net.core.default_qdisc)"
  if [[ $cc_now != "$ST_CC" || $qdisc_now != "$ST_QDISC" ]]; then
    log_warn "sysctl verify: cc=${cc_now}, qdisc=${qdisc_now} (expected ${ST_CC}/${ST_QDISC})"
    rc=3
  fi
  if profile_wants_forwarding; then
    local ct_now
    ct_now="$(sysctl_get net.netfilter.nf_conntrack_max)"
    if [[ $ct_now != "$ST_CONNTRACK" ]]; then
      log_warn "sysctl verify: nf_conntrack_max=${ct_now} (expected ${ST_CONNTRACK})"
      rc=3
    fi
  fi

  log_info "sysctl applied: cc=${cc_now}, qdisc=${qdisc_now}, tier=${ST_TIER}, profile=${ST_PROFILE}"
  return "$rc"
}
