# shellcheck shell=bash
# ============================================================================
# modules/sysctl.sh — kernel network tuning. Implements docs/SYSCTL.md
# exactly: Layer 1 (base) always, Layer 2 forwarding keys for VPN profiles.
# Every written file is tracked via st_track_file for rollback, and every
# apply ends in sysctl_verify() comparing the live kernel to the intent.
# ============================================================================

readonly ST_SYSCTL_FILE='/etc/sysctl.d/99-server-tools.conf'
readonly ST_MODULES_FILE='/etc/modules-load.d/server-tools.conf'
readonly ST_MODPROBE_FILE='/etc/modprobe.d/server-tools.conf'

ST_CC='cubic'
ST_QDISC='fq_codel'

# sysctl_detect_bbr — pick congestion control and queueing discipline.
# The qdisc is probed for real (see qdisc_supported) instead of assumed, and
# an explicit `qdisc` config key wins when the kernel actually supports it.
sysctl_detect_bbr() {
  ST_CC='cubic'
  ST_QDISC='fq_codel'

  if ver_ge "$(kernel_base)" "4.9"; then
    # Kernels with built-in BBR have no module to load; availability is
    # verified against the actual sysctl list right after.
    ((ST_DRY_RUN)) || modprobe tcp_bbr 2>/dev/null || true # absent module is not fatal
    if [[ " $(sysctl_get net.ipv4.tcp_available_congestion_control) " == *bbr* ]]; then
      ST_CC='bbr'
      ST_QDISC='fq'
    fi
  fi

  local wanted
  wanted="$(config_get qdisc auto)"
  if [[ $wanted != auto ]]; then
    if qdisc_supported "$wanted"; then
      ST_QDISC="$wanted"
    else
      log_warn "Configured qdisc '${wanted}' is not supported by this kernel — using ${ST_QDISC}."
    fi
  fi

  if ! qdisc_supported "$ST_QDISC"; then
    log_warn "Kernel does not support ${ST_QDISC} — falling back to fq_codel."
    ST_QDISC='fq_codel'
  fi
  return 0
}

# _sysctl_reserved_ports — listening ports inside our ephemeral range, so an
# outgoing connection can never grab a panel/node listener. Consecutive
# ports are collapsed into ranges, which keeps the value short enough to
# cover far more than a flat list would. Extra ports can be pinned with the
# `reserved_ports` config key (comma separated) for inbounds added later.
_sysctl_reserved_ports() {
  local detected='' extra
  detected="$(listening_service_ports)" || detected=''
  extra="$(config_get reserved_ports '')"
  [[ -n $extra ]] && detected+=$'\n'"${extra//,/$'\n'}"
  [[ -n $detected ]] || return 0

  # Collapse runs of consecutive ports: 11000 11001 11002 -> 11000-11002.
  printf '%s\n' "$detected" |
    grep -E '^[0-9]+$' |
    sort -un |
    awk '
      NR == 1 { start = last = $1; next }
      $1 == last + 1 { last = $1; next }
      { print (start == last ? start : start "-" last); start = last = $1 }
      END { if (NR) print (start == last ? start : start "-" last) }
    ' |
    awk 'NR <= 64' |
    paste -sd, -
}

_sysctl_render() {
  local buf_bytes=$((ST_BUF_MB * 1048576))
  local ram_mb ram_pages swappiness=10 fastopen=3
  ram_mb="$(mem_total_mb)"
  ram_pages=$((ram_mb * 256)) # 4 KiB pages

  # Compressed swap is orders of magnitude faster than a disk swap file, so
  # the kernel should actually use it instead of treating it as a last resort.
  [[ "$(swap_backend_active)" == zram ]] && swappiness=100

  # TCP Fast Open opens an extra fingerprinting surface on servers exposed to
  # DPI, and some middleboxes drop SYNs carrying data. VPN workloads keep the
  # outgoing (client) half only; ordinary servers keep both.
  profile_wants_forwarding && fastopen=1

  cat <<EOF
# Generated by ${ST_NAME} v${ST_VERSION} (profile=${ST_PROFILE}, tier=${ST_TIER})
# The rationale for every key lives in docs/SYSCTL.md:
# ${ST_REPO_URL}

# --- Congestion control & queueing
net.core.default_qdisc = ${ST_QDISC}
net.ipv4.tcp_congestion_control = ${ST_CC}

# --- Connection accept path (tier ${ST_TIER})
net.core.somaxconn = ${ST_SOMAXCONN}
net.ipv4.tcp_max_syn_backlog = ${ST_SOMAXCONN}
net.core.netdev_max_backlog = ${ST_NETDEV_BACKLOG}
net.ipv4.tcp_syncookies = 1

# --- Ports, timers, keepalive
net.ipv4.ip_local_port_range = 10240 65535
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_keepalive_time = 300
net.ipv4.tcp_keepalive_intvl = 60
net.ipv4.tcp_keepalive_probes = 5
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_no_metrics_save = 1
net.ipv4.tcp_fastopen = ${fastopen}
net.ipv4.tcp_notsent_lowat = 16384
# Protect TIME-WAIT sockets from RST assassination (RFC 1337).
net.ipv4.tcp_rfc1337 = 1
# Mode 1 probes only after a blackhole is detected (mode 2 is the harmful one).
net.ipv4.tcp_mtu_probing = 1

# --- Buffers (tier ${ST_TIER})
net.core.rmem_max = ${buf_bytes}
net.core.wmem_max = ${buf_bytes}
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.ipv4.tcp_rmem = 4096 87380 ${buf_bytes}
net.ipv4.tcp_wmem = 4096 65536 ${buf_bytes}
net.ipv4.udp_rmem_min = 16384
net.ipv4.udp_wmem_min = 16384
net.ipv4.udp_mem = $((ram_pages / 32)) $((ram_pages / 16)) $((ram_pages / 8))
net.core.optmem_max = 65536

# --- System capacity
fs.file-max = 2097152
vm.swappiness = ${swappiness}
EOF

  # User-based capacity mode: bound total TCP memory explicitly so buffer
  # autotuning can never crowd a small-RAM host out of userspace memory.
  if ((ST_EXPECTED_USERS > 0)); then
    cat <<EOF

# --- TCP memory bounds (user-based capacity mode: ${ST_EXPECTED_USERS} users)
net.ipv4.tcp_mem = $((ram_pages * 10 / 100)) $((ram_pages * 13 / 100)) $((ram_pages * 16 / 100))
EOF
  fi

  # High-churn caps only where the connection volume justifies them.
  if [[ $ST_TIER == L || $ST_TIER == XL ]]; then
    local tw_buckets=524288 max_orphans=131072
    if [[ $ST_TIER == XL ]]; then
      tw_buckets=1048576
      max_orphans=262144
    fi
    cat <<EOF

# --- High-churn caps (tier ${ST_TIER})
net.ipv4.tcp_max_tw_buckets = ${tw_buckets}
net.ipv4.tcp_max_orphans = ${max_orphans}
EOF
  fi

  local reserved
  reserved="$(_sysctl_reserved_ports)" || reserved=''
  if [[ -n $reserved ]]; then
    cat <<EOF

# --- Listening ports inside the ephemeral range, reserved automatically
net.ipv4.ip_local_reserved_ports = ${reserved}
EOF
  fi

  if profile_wants_forwarding; then
    # UDP conntrack entries dominate the table on QUIC/Hysteria2 nodes: the
    # kernel keeps an assured stream for 120s by default. Proxy traffic keeps
    # flowing (so active flows are refreshed), while WireGuard benefits from
    # longer-lived NAT mappings, hence the profile split.
    local udp_stream=60
    [[ $ST_PROFILE == wireguard ]] && udp_stream=180

    cat <<EOF

# --- VPN workload (profile ${ST_PROFILE}): routing + conntrack + hardening
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1
net.netfilter.nf_conntrack_max = ${ST_CONNTRACK}
# Kernel default is 5 DAYS — idle VPN flows would exhaust the table.
net.netfilter.nf_conntrack_tcp_timeout_established = 3600
net.netfilter.nf_conntrack_tcp_timeout_time_wait = 60
net.netfilter.nf_conntrack_tcp_timeout_close_wait = 30
net.netfilter.nf_conntrack_udp_timeout = 30
net.netfilter.nf_conntrack_udp_timeout_stream = ${udp_stream}
net.netfilter.nf_conntrack_generic_timeout = 300
net.ipv4.conf.all.rp_filter = 2
net.ipv4.conf.default.rp_filter = 2
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
EOF

    # Enabling IPv6 forwarding makes the kernel ignore router advertisements,
    # which silently kills the IPv6 default route on RA/SLAAC providers after
    # a reboot. Value 2 keeps accepting RAs while forwarding.
    # accept_ra is per-device, so the live interface must be named explicitly.
    local iface
    iface="$(net_default_iface)" || iface=''
    cat <<EOF
net.ipv6.conf.all.accept_ra = 2
net.ipv6.conf.default.accept_ra = 2
EOF
    # The leading "-" tells systemd-sysctl to ignore this line when the
    # interface does not exist yet at early boot, instead of logging a error.
    [[ -n $iface ]] && printf -- '-net.ipv6.conf.%s.accept_ra = 2\n' "$iface"
  fi

  # This helper's stdout is captured via `rendered="$(_sysctl_render)"`. Under
  # errexit a bare assignment propagates the callee's exit status, so a
  # trailing conditional evaluating false (e.g. the accept_ra guard above on a
  # host with no default route) would trip the ERR trap and abort the run.
  # Value-producing helpers must therefore always return success explicitly.
  return 0
}

# _ports_expand LIST — "80,1000-1002" -> a sorted, space separated port set.
# The kernel normalises ip_local_reserved_ports (it stores a bitmap and
# prints merged ranges), so that key can only be compared as a set.
_ports_expand() {
  local item low high
  {
    for item in ${1//,/ }; do
      if [[ $item == *-* ]]; then
        low="${item%%-*}"
        high="${item##*-}"
        [[ $low =~ ^[0-9]+$ && $high =~ ^[0-9]+$ ]] || continue
        while ((low <= high)); do
          printf '%s\n' "$low"
          low=$((low + 1))
        done
      elif [[ $item =~ ^[0-9]+$ ]]; then
        printf '%s\n' "$item"
      fi
    done
  } | sort -un | paste -sd' ' -
}

# _sysctl_values_match KEY ACTUAL EXPECTED
_sysctl_values_match() {
  case "$1" in
    net.ipv4.ip_local_reserved_ports)
      [[ "$(_ports_expand "$2")" == "$(_ports_expand "$3")" ]]
      ;;
    *)
      # Normalise whitespace runs so multi-value keys compare fairly.
      [[ "$(tr -s ' \t' ' ' <<<"$2")" == "$(tr -s ' \t' ' ' <<<"$3")" ]]
      ;;
  esac
}

# sysctl_verify [RENDERED] — compare the live kernel against the intent of
# this profile. Returns 0 when everything matches, 3 on drift.
# The caller passes the text it actually wrote: re-rendering here would read
# live inputs again (listening ports, swap backend) and could compare against
# a different expectation than the one on disk.
ST_SYSCTL_DRIFT=()

sysctl_verify() {
  ST_SYSCTL_DRIFT=()
  local rendered="${1:-}" line key expected actual
  [[ -n $rendered ]] || rendered="$(_sysctl_render)"

  while IFS= read -r line; do
    [[ -z $line || $line == \#* ]] && continue
    expected="${line#*=}"
    expected="${expected#"${expected%%[![:space:]]*}"}"
    key="${line%%=*}"
    key="${key//[[:space:]]/}"
    key="${key#-}" # a leading "-" only tells systemd to ignore failures
    actual="$(sysctl_get "$key")"
    _sysctl_values_match "$key" "$actual" "$expected" ||
      ST_SYSCTL_DRIFT+=("${key}|${actual}|${expected}")
  done <<<"$rendered"

  ((${#ST_SYSCTL_DRIFT[@]} == 0)) && return 0
  return 3
}

# sysctl_dry_run — render the exact config this run would write and diff
# every key against the live kernel. Applies NOTHING and tracks nothing.
sysctl_dry_run() {
  sysctl_detect_bbr
  local rendered
  rendered="$(_sysctl_render)"
  printf '%s[Rendered %s]%s\n%s\n\n' "$C_TITLE" "$ST_SYSCTL_FILE" "$C_RESET" "$rendered"
  printf '%s[Diff vs live kernel]%s\n' "$C_TITLE" "$C_RESET"

  local entry key actual expected total
  total="$(grep -cE '^-?[a-z]' <<<"$rendered")"
  sysctl_verify "$rendered" || true # drift is the expected outcome here
  if ((${#ST_SYSCTL_DRIFT[@]} == 0)); then
    printf '  (kernel already matches this profile)\n'
  else
    # Guarded: iterating "${arr[@]-}" on an empty array yields one empty
    # element, which would print a bare "->" row.
    for entry in "${ST_SYSCTL_DRIFT[@]}"; do
      IFS='|' read -r key actual expected <<<"$entry"
      printf '  %s%-50s%s %s -> %s\n' "$C_KEY" "$key" "$C_RESET" "$actual" "$expected"
    done
  fi
  printf '\n%s%d of %d keys would change. Nothing was applied.%s\n' \
    "$C_WARN" "${#ST_SYSCTL_DRIFT[@]}" "$total" "$C_RESET"
}

sysctl_apply() {
  if ! has_cmd sysctl; then
    log_error "sysctl command not found — cannot tune the kernel."
    return 1
  fi

  sysctl_detect_bbr

  local modules=()
  [[ $ST_CC == bbr ]] && modules+=(tcp_bbr)

  if profile_wants_forwarding; then
    # Without the module loaded, net.netfilter.* keys silently fail to apply.
    modprobe nf_conntrack 2>/dev/null ||
      log_warn "nf_conntrack module unavailable — conntrack keys may not apply."
    modules+=(nf_conntrack)
  fi

  # Rendered exactly once: the same text is written and later verified.
  local rendered
  rendered="$(_sysctl_render)"

  st_track_file "$ST_SYSCTL_FILE"
  mkdir -p "$(dirname "$ST_SYSCTL_FILE")"
  printf '%s\n' "$rendered" >"$ST_SYSCTL_FILE"

  if ((${#modules[@]} > 0)); then
    st_track_file "$ST_MODULES_FILE"
    mkdir -p "$(dirname "$ST_MODULES_FILE")"
    {
      printf '# Generated by %s v%s\n' "$ST_NAME" "$ST_VERSION"
      printf '%s\n' "${modules[@]}"
    } >"$ST_MODULES_FILE"
  fi

  if profile_wants_forwarding; then
    # The conntrack hash table must scale with the table itself; the runtime
    # knob is a module parameter, persisted for reboots via modprobe.d.
    local hashsize=$((ST_CONNTRACK / 4))
    st_track_file "$ST_MODPROBE_FILE"
    mkdir -p "$(dirname "$ST_MODPROBE_FILE")"
    printf '# Generated by %s v%s\noptions nf_conntrack hashsize=%s\n' \
      "$ST_NAME" "$ST_VERSION" "$hashsize" >"$ST_MODPROBE_FILE"
    if [[ -w /sys/module/nf_conntrack/parameters/hashsize ]]; then
      printf '%s' "$hashsize" >/sys/module/nf_conntrack/parameters/hashsize 2>>"$ST_LOG_FILE" ||
        log_warn "Could not resize the conntrack hash table live (persisted for next boot)."
    fi
  fi

  # Apply; per-key errors land in the log instead of vanishing — the result
  # is verified against the live kernel right after.
  sysctl --system >/dev/null 2>>"$ST_LOG_FILE" || true

  # default_qdisc only affects NEW interfaces; switch the live default
  # interface too so the change is complete without a reboot.
  local iface
  iface="$(net_default_iface)" || iface=''
  if [[ -n $iface ]] && has_cmd tc; then
    tc qdisc replace dev "$iface" root "$ST_QDISC" 2>>"$ST_LOG_FILE" ||
      log_warn "Could not switch ${iface} to ${ST_QDISC} live (it applies after reboot)."
  fi

  local rc=0
  if ! sysctl_verify "$rendered"; then
    local entry key actual expected names=''
    for entry in "${ST_SYSCTL_DRIFT[@]}"; do
      IFS='|' read -r key actual expected <<<"$entry"
      names+="${key} "
      log_info "drift: ${key} is '${actual}', expected '${expected}'"
    done
    log_warn "${#ST_SYSCTL_DRIFT[@]} key(s) did not take the expected value: ${names% }"
    rc=3
  fi

  log_info "sysctl applied: cc=$(sysctl_get net.ipv4.tcp_congestion_control), qdisc=${ST_QDISC}, tier=${ST_TIER}, profile=${ST_PROFILE}"
  return "$rc"
}
