# shellcheck shell=bash
# ============================================================================
# modules/vpn.sh — VPN-aware non-sysctl fixes.
#
# MSS clamping is the most common fix for "WireGuard connects but pages
# don't load" behind NAT. Persistence uses a systemd ONESHOT unit: it runs
# once at boot and exits — no resident process, zero-footprint compliant.
# ============================================================================

readonly ST_MSS_UNIT='/etc/systemd/system/server-tools-mss.service'
# The comma in SYN,RST is iptables syntax, not an array-separator mistake.
# shellcheck disable=SC2054
readonly -a ST_MSS_RULE=(
  FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
)

vpn_mss_clamp() {
  ui_section "MSS clamping (TCP over tunnels/NAT)"
  printf 'Clamps TCP MSS to the path MTU on forwarded traffic. Fixes the classic\n'
  printf '"VPN connects but sites do not load" symptom (WireGuard, tunnels, NAT).\n'
  if ! has_cmd iptables; then
    log_error "iptables not available — cannot apply MSS clamping."
    return 0
  fi
  ui_confirm "Apply MSS clamping now?" || return 0

  if ! iptables -t mangle -C "${ST_MSS_RULE[@]}" 2>/dev/null; then
    if ! iptables -t mangle -A "${ST_MSS_RULE[@]}" 2>>"$ST_LOG_FILE"; then
      log_error "Could not add the IPv4 MSS rule — see the log."
      return 0
    fi
  fi
  if has_cmd ip6tables && ! ip6tables -t mangle -C "${ST_MSS_RULE[@]}" 2>/dev/null; then
    ip6tables -t mangle -A "${ST_MSS_RULE[@]}" 2>>"$ST_LOG_FILE" ||
      log_warn "IPv6 MSS rule failed (IPv6 clamping skipped)."
  fi

  if [[ -d /etc/systemd/system ]] && has_cmd systemctl; then
    local ipt ip6t
    ipt="$(command -v iptables)"
    ip6t="$(command -v ip6tables)" || ip6t=''
    st_track_file "$ST_MSS_UNIT"
    {
      printf '# Generated by %s v%s\n' "$ST_NAME" "$ST_VERSION"
      printf '[Unit]\nDescription=ServerTools MSS clamping (oneshot, exits after boot)\nAfter=network-pre.target\nWants=network-pre.target\n\n'
      printf '[Service]\nType=oneshot\nRemainAfterExit=yes\n'
      printf 'ExecStart=%s -t mangle -A %s\n' "$ipt" "${ST_MSS_RULE[*]}"
      [[ -n $ip6t ]] && printf 'ExecStart=%s -t mangle -A %s\n' "$ip6t" "${ST_MSS_RULE[*]}"
      printf '\n[Install]\nWantedBy=multi-user.target\n'
    } >"$ST_MSS_UNIT"
    systemctl daemon-reload 2>>"$ST_LOG_FILE" || log_warn "daemon-reload failed."
    if systemctl enable server-tools-mss.service >/dev/null 2>>"$ST_LOG_FILE"; then
      manifest_add unit server-tools-mss.service
    else
      log_warn "Could not enable boot persistence for the MSS rule."
    fi
  else
    log_warn "No systemd — the MSS rule is active now but will not survive a reboot."
  fi

  printf '%sMSS clamping active%s (persisted via oneshot unit — nothing stays running).\n' \
    "$C_OK" "$C_RESET"
  log_info "MSS clamping applied."
}

vpn_docker_ufw_audit() {
  ui_section "Docker + UFW audit"
  local docker_on=0 ufw_on=0
  if has_cmd docker && docker ps -q 2>/dev/null | grep -q .; then
    docker_on=1
  fi
  if has_cmd ufw && ufw status 2>/dev/null | grep -q '^Status: active'; then
    ufw_on=1
  fi

  if ((docker_on == 0)); then
    printf 'No running Docker containers — no bypass risk.\n'
    return 0
  fi
  if ((ufw_on == 0)); then
    printf 'Docker is running but UFW is inactive — nothing to bypass (no firewall).\n'
    return 0
  fi

  printf '%sBoth Docker and UFW are active.%s Docker inserts its own iptables rules,\n' "$C_WARN" "$C_RESET"
  printf 'so ports published with -p/ports: are reachable EVEN IF UFW blocks them.\n'
  printf '\n%sPublished ports right now:%s\n' "$C_KEY" "$C_RESET"
  docker ps --format '  {{.Names}}: {{.Ports}}' 2>/dev/null ||
    log_warn "Could not list container ports."
  printf '\nMitigations: bind sensitive ports to 127.0.0.1 in compose, or use the\n'
  printf 'ufw-docker approach (planned in ROADMAP.md backlog).\n'
}
